# Generated by Django 5.1.1 on 2024-09-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='balance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
