# Generated by Django 5.1.1 on 2024-09-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0003_transaction_transaction_type_alter_balance_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
        migrations.AlterField(
            model_name='balance',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
