# Generated by Django 5.1.1 on 2024-10-04 10:36

import sacco.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0005_transaction_transaction_type_alter_balance_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=sacco.models.generate_short_uuid, editable=False, primary_key=True, serialize=False),
        ),
    ]
