# Generated by Django 5.1.1 on 2024-10-04 10:38

import sacco.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0006_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=sacco.models.generate_short_uuid, editable=False, max_length=12, primary_key=True, serialize=False),
        ),
    ]
