# Generated by Django 5.1.2 on 2025-05-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0009_transaction_balance_after_transaction_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_secretary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_tresurer',
            field=models.BooleanField(default=False),
        ),
    ]
